name: GO LINT CHECK
on:
  push:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install GO Lint
        run: go install golang.org/x/lint/golint@latest

      - name: Run The Go Lint
        run: go lint ./assignment1go


