name: GO LINT CHECK
on:
  push:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install GO Lint
        run: go mod download

      - name: Run The Go Lint
        run: golangci/golangci-lint-action@v7
        with:
          version: v2.1.6

